pipeline {
  agent any
  environment {
    DOTNET_CLI_TELEMETRY_OPTOUT = "1"
    IMAGE = "monprojetpfe:latest"
    K8S_NS = "monprojetpfe"
    SONARQUBE_INSTANCE = "sonarqube"   // nom dans Jenkins Global Config
    HOME = "/var/lib/jenkins"
  }
  stages {
    stage('Checkout') { steps { checkout scm } }

    stage('Restore/Build/Test') {
      steps {
        sh 'dotnet --info'
        sh 'dotnet restore src/MonProjetPFE.csproj'
        sh 'dotnet build -c Release src/MonProjetPFE.csproj'
        sh 'dotnet test src/MonProjetPFE.csproj -c Release --no-build --logger "trx"'
      }
    }

    stage('SonarQube Analysis') {
      environment { SONAR_TOKEN = credentials('sonar-token') }
      steps {
        withSonarQubeEnv("${env.SONARQUBE_INSTANCE}") {
          sh '''
          dotnet tool install --global dotnet-sonarscanner || true
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet-sonarscanner begin /k:"MonProjetPFE" /d:sonar.login="$SONAR_TOKEN"
          dotnet build -c Release src/MonProjetPFE.csproj
          dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"
          '''
        }
      }
    }

    stage('Docker Build (local)') {
  steps {
    sh '''
    minikube image build -t $IMAGE -f infra/docker/Dockerfile .
    minikube image load $IMAGE
    '''
  }
}


    stage('Deploy to Minikube') {
  steps {
    sh '''
    echo "Déploiement sur Minikube..."
    kubectl apply -f infra/k8s/storageclass.yaml --validate=false
    kubectl apply -f infra/k8s/namespace.yaml --validate=false
    kubectl -n $K8S_NS apply -f infra/k8s/pv.yaml --validate=false

    # Supprimer le deployment et le pod avant de modifier le PVC
    kubectl -n $K8S_NS delete deployment portal --ignore-not-found=true
    kubectl -n $K8S_NS delete pod -l app=portal --ignore-not-found=true

    # Supprimer le PVC s’il existe
    if kubectl -n $K8S_NS get pvc portal-pvc > /dev/null 2>&1; then
      echo "PVC déjà existant. Suppression pour éviter conflit..."
      kubectl -n $K8S_NS delete pvc portal-pvc
    fi

    kubectl -n $K8S_NS apply -f infra/k8s/pvc.yaml --validate=false
    kubectl -n $K8S_NS apply -f infra/k8s/deployment.yaml --validate=false
    kubectl -n $K8S_NS apply -f infra/k8s/service.yaml --validate=false
    kubectl -n $K8S_NS apply -f infra/k8s/ingress.yaml --validate=false
    kubectl -n $K8S_NS rollout status deploy/portal

    '''
  }
}

  }
  post {
    always {
      archiveArtifacts artifacts: '**/*.trx', allowEmptyArchive: true
    }
  }
}
