apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /tmp/portal-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: monprojetpfe
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  volumeName: portal-pv
